
name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
           - uses: actions/checkout@v3
           - name: use Node.js
             uses: actions/setup-node@v3
             with:
                 node-version: 18.12.1
                 cache: npm
           - name: Install Dependencies
             run: npm install 
           - name: setup Latest Chrome Driver
             run: npm run chromeDriverUpdate
           - name: Executing the Test Scripts
             run: npm run makeMyTrip
           - name: Deploy report to Github Pages
             if: always()
             uses: peaceiris/actions-gh-pages@v2
             env:
               PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               PUBLISH_BRANCH: gh-pages
               PUBLISH_DIR: allure-history
